apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit
  template:
    metadata:
      labels:
        app: reddit
    spec:
      containers:
      - name: reddit-container
        #image: gcr.io/mlops-lab-9-458608/reddit-app
        image: reddit-app:latest
        #imagePullPolicy: Always
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
